apiVersion: apps/v1
kind: Deployment
metadata:
  name: md-getway-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: md-getway-go
  template:
    metadata:
      labels:
        app: md-getway-go
    spec:
      hostNetwork: true  # Añade esta línea para usar la red del host
      dnsPolicy: ClusterFirstWithHostNet  # Ajusta la política de DNS adecuada para hostNetwork
      containers:
      - name: md-getway-go
        image: md-getway-go:15
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8070
